#+TITLE:     marius.org
#+AUTHOR:    Marius Mathiesen
#+EMAIL:     zmalltalker@zmalltalker.com
#+DATE:      2012-07-06 Fri
#+DESCRIPTION: My emacs configuration
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

* Dot emacs, literate style

  This file is loaded from init.el after any .org files in extras/
  This is because we want to be able to use libraries from there from this file.

** Ido
    Ido improves all kind of minibuffer activities:
    - find-file
    - switch-buffer
      
    with case-insensitivity and all kinds of wonderful things. Let's
    load it up: 

#+begin_src emacs-lisp
(load-library "ido")
(ido-mode)
#+end_src

** Emacs server mode
   Let's support emacsclient. For that to work, we'll need to start the server.
   Unless, of course, it's already running

#+begin_src emacs-lisp
(require 'server)
(unless (server-running-p) (server-start))
#+end_src

** YAML mode

   YAML is ... should we say picky? ... to edit by hand. Indentation
   matters a lot, and syntax highlighting is a great help. 

   Let's get some help:

#+begin_src emacs-lisp
(require 'yaml-mode)
(add-to-list 'auto-mode-alist '("\\.yml$" . yaml-mode))
#+end_src


** Packages

   Emacs 24 ships with a package system, which is great. 
   Let's enable it:

#+begin_src emacs-lisp
(package-initialize)
#+end_src 

   and add some more repositories:

#+begin_src emacs-lisp
(add-to-list 'package-archives
             '("marmalade" . "http://marmalade-repo.org/packages/"))
#+end_src


** Magnar's awesome Magit setup
   Magit. I was skeptical at first, but then I just ... yum. 
   Let's load it

#+begin_src emacs-lisp
(require 'magit)
(add-to-list 'load-path "/home/marius/.emacs.d/extras")
#+end_src

   Magnar (or Christian?) shared some customizations for Magit
   that make it even better:

#+begin_src emacs-lisp
(require 'setup-magit) 
#+end_src

   I use C-x m for starting magit
   
#+begin_src emacs-lisp
(global-set-key (kbd "C-x m") 'magit-status)
#+end_src

** Recent files
   Support open-recent-file. This needs some work.

#+begin_src emacs-lisp
(require 'recentf)
(recentf-mode 1)
#+end_src

** Textmate mode
   I kept missing jump to symbol in Emacs after getting rid of the
   crutches that were the starter kit. I discovered Chris Wanstrath's
   textmate-mode, which provides this and a lot more.

   The thing is, I don't like the key bindings used there; plus there
   are a lot of Textmate features I don't care about. In the process
   of adjusting it to my needs, I decided to use org-babel for it instead.

#+begin_src emacs-lisp
(textmate-mode)
#+end_src
   

* My Emacs installation
  My OS (Fedora 17) ships with Emacs 24 (doesn't yours?). Sadly this
  version doesn't work 100% with all of the orgmode features, either
  because it's a prerelease version or because it's poorly built.

  Whenever I try to run org-export, I get an error along the lines of
  "cannot find library org"; trying to resolve this by altering
  org-mode just seems to make matters worse.

  Because of this I have built and installed emacs 24.1 from source,
  and then used the alternatives system to swap the default Emacs
  installation with my own.

  I used [[http://jonebird.com/2011/12/29/installing-emacs-v24-on-fedora/][this recipe]] to install the required packages for building
  emacs, installed my custom emacs into a non-standard location
  (/usr/local/emacs24) and used alternatives to swap emacs
  implementation. 
